import type { Event, Artist, HeroSlide } from "@/types";

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: "h1",
    title: "Tu Evento\nmás Esperado",
    subtitle: "15 Julio · WiZink Center · Madrid",
    tag: "Concierto",
    city: "Madrid",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Concierto en el WiZink Center, Madrid",
    ctaPrimary: "Comprar entradas",
    ctaSecondary: "Ver detalles",
    href: "/evento/concierto-wizink",
  },
  {
    id: "h2",
    title: "Festival\nde Verano",
    subtitle: "20–22 Agosto · Fòrum · Barcelona",
    tag: "Festival",
    city: "Barcelona",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Festival de verano en Barcelona",
    ctaPrimary: "Comprar entradas",
    href: "/evento/festival-verano",
  },
  {
    id: "h3",
    title: "La Gran\nObra",
    subtitle: "Todo septiembre · Teatro Lope de Vega · Sevilla",
    tag: "Teatro",
    city: "Sevilla",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Obra de teatro en Sevilla",
    ctaPrimary: "Comprar entradas",
    href: "/evento/la-gran-obra",
  },
];

export const EVENTS: Event[] = [
  {
    id: "e1",
    slug: "artista-principal-madrid",
    title: "Artista Principal en Concierto",
    artist: "Artista Principal",
    category: "musica",
    date: "Sáb 12 Jul",
    dateISO: "2025-07-12",
    venue: "WiZink Center",
    city: "Madrid",
    country: "España",
    price: 35,
    priceLabel: "Desde 35€",
    image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=600&q=80",
    imageAlt: "Concierto de Artista Principal en Madrid",
    tags: ["Concierto", "Madrid"],
    description: "Una noche inolvidable con los mejores éxitos en directo.",
    featured: true,
    soldOut: false,
    capacity: 18000,
    ticketsLeft: 340,
  },
  {
    id: "e2",
    slug: "festival-internacional-barcelona",
    title: "Festival Internacional de Música",
    category: "festivales",
    date: "20–22 Ago",
    dateISO: "2025-08-20",
    venue: "Fòrum",
    city: "Barcelona",
    country: "España",
    price: 60,
    priceLabel: "Desde 60€",
    image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=600&q=80",
    imageAlt: "Festival Internacional de Música en Barcelona",
    tags: ["Festival", "Barcelona"],
    description: "Tres días de música, cultura y experiencias únicas.",
    featured: true,
    soldOut: false,
    capacity: 25000,
    ticketsLeft: 1200,
  },
  {
    id: "e3",
    slug: "gran-obra-teatro-sevilla",
    title: "La Gran Obra de Teatro",
    category: "teatro",
    date: "Todo septiembre",
    dateISO: "2025-09-01",
    venue: "Teatro Lope de Vega",
    city: "Sevilla",
    country: "España",
    price: 25,
    priceLabel: "Desde 25€",
    image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=600&q=80",
    imageAlt: "Obra de teatro en Sevilla",
    tags: ["Teatro", "Sevilla"],
    description: "La obra que ha emocionado a toda España llega a Sevilla.",
    featured: false,
    soldOut: false,
    capacity: 800,
    ticketsLeft: 42,
  },
  {
    id: "e4",
    slug: "final-temporada-liga-valencia",
    title: "Final de Temporada Liga",
    category: "deportes",
    date: "Dom 30 Jun",
    dateISO: "2025-06-30",
    venue: "Estadio Mestalla",
    city: "Valencia",
    country: "España",
    price: 45,
    priceLabel: "Desde 45€",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=600&q=80",
    imageAlt: "Final de temporada en Mestalla",
    tags: ["Deportes", "Valencia"],
    description: "El partido que decidirá el campeón de la temporada.",
    featured: false,
    soldOut: true,
    capacity: 55000,
    ticketsLeft: 0,
  },
  {
    id: "e5",
    slug: "standup-comedy-bilbao",
    title: "Noche de Stand-up Comedy",
    category: "comedia",
    date: "Vie 5 Jul",
    dateISO: "2025-07-05",
    venue: "Teatro Arriaga",
    city: "Bilbao",
    country: "España",
    price: 18,
    priceLabel: "Desde 18€",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=600&q=80",
    imageAlt: "Noche de comedia en Bilbao",
    tags: ["Comedia", "Bilbao"],
    description: "Los mejores monologuistas del país en una sola noche.",
    featured: false,
    soldOut: false,
    capacity: 600,
    ticketsLeft: 78,
  },
  {
    id: "e6",
    slug: "circo-maravillas-zaragoza",
    title: "Circo de las Maravillas",
    category: "familia",
    date: "Todo julio",
    dateISO: "2025-07-01",
    venue: "Palacio de Congresos",
    city: "Zaragoza",
    country: "España",
    price: 22,
    priceLabel: "Desde 22€",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80",
    imageAlt: "Circo de las Maravillas en Zaragoza",
    tags: ["Familia", "Zaragoza"],
    description: "Magia, acrobacia y diversión para toda la familia.",
    featured: false,
    soldOut: false,
    capacity: 2000,
    ticketsLeft: 510,
  },
  {
    id: "e7",
    slug: "exposicion-arte-contemporaneo-madrid",
    title: "Exposición Arte Contemporáneo",
    category: "arte",
    date: "Jun–Sep",
    dateISO: "2025-06-01",
    venue: "Museo Reina Sofía",
    city: "Madrid",
    country: "España",
    price: 14,
    priceLabel: "Desde 14€",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=600&q=80",
    imageAlt: "Exposición de arte contemporáneo en Madrid",
    tags: ["Arte", "Madrid"],
    description: "Las tendencias más innovadoras del arte del siglo XXI.",
    featured: false,
    soldOut: false,
    capacity: 500,
    ticketsLeft: 200,
  },
  {
    id: "e8",
    slug: "jazz-festival-malaga",
    title: "Festival de Jazz Internacional",
    category: "musica",
    date: "Vie–Dom 12–14 Jul",
    dateISO: "2025-07-12",
    venue: "Auditorio Municipal",
    city: "Málaga",
    country: "España",
    price: 50,
    priceLabel: "Desde 50€",
    image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&amp;fit=crop&amp;w=600&amp;q=80",
    imageAlt: "Festival de Jazz en Málaga",
    tags: ["Música", "Málaga"],
    description: "Tres noches de puro jazz con artistas internacionales.",
    featured: true,
    soldOut: false,
    capacity: 3500,
    ticketsLeft: 88,
  },
];

export const ARTISTS: Artist[] = [
  { id: "a1", name: "Luna Verde",   genre: "Indie Pop",  image: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&w=200&q=80", slug: "luna-verde" },
  { id: "a2", name: "Marcos Días",  genre: "Flamenco",   image: "https://images.unsplash.com/photo-1517502166878-35c93a0072bb?auto=format&fit=crop&w=200&q=80", slug: "marcos-dias" },
  { id: "a3", name: "Neon Collective",genre:"Electrónica",image: "https://images.unsplash.com/photo-1511376777868-611b54f68947?auto=format&fit=crop&w=200&q=80", slug: "neon-collective" },
  { id: "a4", name: "Sofia & Band", genre: "Jazz",       image: "https://images.unsplash.com/photo-1518972559570-1f5f52ecf5bc?auto=format&fit=crop&w=200&q=80", slug: "sofia-band" },
  { id: "a5", name: "El Trío",      genre: "Clásica",    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=200&q=80", slug: "el-trio" },
  { id: "a6", name: "Rebelde Sur",  genre: "Rock",       image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=200&q=80", slug: "rebelde-sur" },
  { id: "a7", name: "Salsa Brava",  genre: "Latino",     image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=200&q=80", slug: "salsa-brava" },
  { id: "a8", name: "Trio Urbano",  genre: "Hip-hop",    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=200&q=80", slug: "trio-urbano" },
];

export const CATEGORIES = [
  { id: "musica",    label: "Música",    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1400&q=80" },
  { id: "festivales",label: "Festivales",image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=400&q=80" },
  { id: "teatro",    label: "Teatro",    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=400&q=80" },
  { id: "deportes",  label: "Deportes",  image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=400&q=80" },
  { id: "familia",   label: "Familia",   image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=400&q=80" },
  { id: "comedia",   label: "Comedia",   image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=400&q=80" },
  { id: "arte",      label: "Arte",      image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=400&q=80" },
] as const;
